.github/workflows/test.yaml, requirements-test.txt, xgboost_ray/matrix.py, xgboost_ray/tests/test_matrix.py, xgboost_ray/tune.py, xgboost_ray/util.py
Currently only in central data loading mode. Integration with distributed mode would require more access to private modin functions - we can look into this at another time.
This PR also adds (and fixes) compatibility tests for the latest ray release when some dependencies are not installed. E.g. if Tune or Modin are not installed, certain tests and examples should still run.
=> Add support for modin dataframes

README.md
There's not much to do to reduce peak memory usage. Thus we should just document things to consider and best practices.
=> Update README for peak memory usage suggestions

xgboost_ray/tune.py
Since we inherit from the Ray Tune-specific callbacks, the callbacks were replaced and a warning was thrown even if it wasn't necessary.
=> Only replace callbacks if necessary (removes unnecessary Tune warning)

README.md, xgboost_ray/main.py, xgboost_ray/tests/test_tune.py, xgboost_ray/tune.py
Currently, we are reporting results from every actor. This leads to a double reports and a blown up iteration count. Instead, we should just report results from the 0 rank actor.
=> Tune reporting

README.md, xgboost_ray/tests/test_colocation.py
It seems that indeed the second test is started prematurely. The output is misleading.
Waiting for cluster nodes to be ready seems to be at the core of this problem, and it should be safe to do this in any case.
=> fix colocation test

README.md, xgboost_ray/main.py, xgboost_ray/matrix.py, xgboost_ray/tests/test_end_to_end.py, xgboost_ray/tests/test_tune.py
These changes automatically detect if xgboost_ray is running in client mode, and if this is the case, will run the `train()` and `predict()` methods in remote function calls. 
Closes #53
=> Allow train and predict to run in remote function, enabling Ray client mode

xgboost_ray/main.py, xgboost_ray/tests/test_tune.py
When using with Tune, resources should all be specified by the user in RayParams instead of autodetecting during training. This is to avoid any discrepancies between the resources that Tune reserves for each trial, and the resources that each trial actually uses.
=> Don't autodetect resources when using with Tune

xgboost_ray/main.py, xgboost_ray/matrix.py
RayDeviceQuantileDMatrix became incompatible with recent changes. This PR makes sure it works again.
Please note that we currently have no general support to load from files into GPU memory directly, avoiding CPU memory. Thus the RayDeviceQuantileDMatrix works with conversion (or when cupy arrays are provided directly). In the future we might want to introduce interfaces for loading from files into GPU memory.
Closes #65
=> Fix RayDeviceQuantileDMatrix

xgboost_ray/callback.py, xgboost_ray/elastic.py, xgboost_ray/main.py, xgboost_ray/tests/test_end_to_end.py
This PR adds a callback interface to RayXGBoostActor. This has been a request in #49 and we'll use it for more fine-grained fault tolerance testing - we can e.g. control when actors are allowed to come back after they terminated.
The parameter and class are called "distributed callback" to set them apart from the regular xgboost training callbacks.
Closes #49
=> Add distributed callback interface to RayXGBoostActor

xgboost_ray/main.py
Even if Ray Tune supports placement groups, they are currently not enforced. Thus, we shouldn't throw an error when people are using Tune without PGs.
=> Better PG check for Ray Tune

xgboost_ray/main.py
Currently the actor local n is overridden when loading any data. This means that usually the length of the last evaluation dataset is returned instead of the last training dataset.
=> Fix local n calculation

xgboost_ray/data_sources/data_source.py, xgboost_ray/data_sources/numpy.py, xgboost_ray/main.py, xgboost_ray/matrix.py
Converting numpy arrays to pandas dataframes for sharding implicitly adds coluimn names which are stored in the reuslting xgboost booster objects. However, calling `predict` on such boosters with numpy arrays leads to errors. Instead we should unset feature names for numpy arrays if they haven't been deliberately passed to `RayDMatrix`.
=> Compatibility with xgboost 1.4 (remove feature names form numpy arrays)

xgboost_ray/main.py
Closes issue discussed in #80
Should we raise an error instead?
=> Show warning if gpus are assigned but tree method is incompatible

xgboost_ray/data_sources/csv.py, xgboost_ray/data_sources/data_source.py, xgboost_ray/data_sources/parquet.py, xgboost_ray/data_sources/petastorm.py, xgboost_ray/main.py, xgboost_ray/matrix.py, xgboost_ray/tests/test_matrix.py
Closes #12, concerns #81
Currently we don't check if we assign too many actors to too few data shards. This PR introduces a check that will raise an error if we assign too many workers to too few data sources, which would leave some actors without any data to train on.
=> Raise an error if actors would end up without any data

xgboost_ray/main.py
* `get_resource_ids` are being moved out of the top level `ray` API in this [Ray PR](https://github.com/ray-project/ray/pull/15440).
=> [Private APIs] Switch to `ray.worker.get_resource_ids`

.github/workflows/test.yaml, examples/simple.py, format.sh, setup.py, xgboost_ray/compat/__init__.py, xgboost_ray/compat/tracker.py, xgboost_ray/main.py, xgboost_ray/matrix.py, xgboost_ray/tests/release/tune_placement.py, xgboost_ray/tests/test_fault_tolerance.py, xgboost_ray/tests/test_xgboost_api.py, xgboost_ray/tests/utils.py, xgboost_ray/tune.py
=> Compatibility for xgboost 0.90

xgboost_ray/main.py, xgboost_ray/session.py, xgboost_ray/tune.py
Currently we're using the XGBoost-Ray generated actor ranks (that differ from those assigned by Rabit) to decide which actor should report checkpoints or Tune results back to the driver.
This is faulty in elastic training: If the rank 0 actor dies and the other actors continue training, no checkpoints or tune results will be reported back.
With this PR, we use the Rabit-provided ranks instead. Rabit always assigns ranks anew, starting with rank 0, so this guarantees we will always have an actor reporting results and checkpoints.
=> Use rabit ranks instead of xgboost-ray-ranks for checkpointing and result reporting

xgboost_ray/main.py
Currently each actor returns the trained Booster object.
This is inefficient:
1. All Booster objects are the same
2. Transferring large Boosters over slow networks can lead to much overhead
3. We call `ray.get()` three times on each of the training futures. Although results should be cached, this doesn't always seem to be the case
Instead, only the first live training actor should return its Booster object. 
Also, we want to minimize the number of calls to `ray.get()`.
This should fix an issue that came up training with 150 workers where each individual result fetch would take about 2 seconds to complete.
cc @mmui
=> Only one remote actor should return its Booster

.github/workflows/test.yaml, examples/simple_dask.py, run_ci_examples.sh, xgboost_ray/data_sources/__init__.py, xgboost_ray/data_sources/_distributed.py, xgboost_ray/data_sources/dask.py, xgboost_ray/data_sources/modin.py, xgboost_ray/tests/release/cluster_cpu.yaml, xgboost_ray/tests/test_data_source.py, xgboost_ray/tests/test_matrix.py
Closes #92
Note that the locality-aware scheduling can currently not be tested reliably. This is due to 2 reasons:
1) We cannot guarantee that dask partitions end up living on a specific node (to set an initial state for redistribution)
2) We cannot guarantee that tasks that determine the dask partition node are co-scheduled with the respective partition.
Once the `ray.state.objects()` API or something similar comes back, the second option should be easy to enable, and the first option will be easy to confirm.
=> Add support for dask dataframes

xgboost_ray/callback.py, xgboost_ray/main.py, xgboost_ray/matrix.py, xgboost_ray/tests/test_end_to_end.py
`objective="multi:softprob"` returns a 2d array instead of a 1d array during prediction. This caused issues with `predict` as it expected a 1d array. This PR fixes this, as well as the handling of BATCH sharding mode during prediction (though I think it still fails on training).
The only change to the public API would be that the callback receives a pandas DataFrame instead of a Series, but I don't think it will cause many issues.
A test was added.
=> Fix issues with objective="multi:softprob"

run_ci_examples.sh, run_ci_tests.sh, xgboost_ray/main.py, xgboost_ray/tests/fault_tolerance.py, xgboost_ray/tests/test_colocation.py, xgboost_ray/tests/test_data_source.py, xgboost_ray/tests/test_fault_tolerance.py, xgboost_ray/tests/test_sklearn.py
This PR makes the CI scripts exit with correct status if at least one test fails. Previously, no matter what the test results were, the CI always passed (aside from linting). This may uncover some bad tests/errors that were not noticed before.
The `run_ci_tests.sh` script was made so that all tests will run instead of exiting CI as soon as a pytest invocation fails in order to simplify debugging. Same could be done for examples but I don't think it's worth it.
=> Fail CI if tests do not pass

xgboost_ray/main.py, xgboost_ray/tests/test_data_source.py
Please read https://github.com/ray-project/ray/issues/16507 for the bug and context.
Here is a summary:
- After #[16437](https://github.com/ray-project/ray/pull/16437) the Actor placement behavior [has changed for ](https://github.com/ray-project/ray/pull/16437/files#diff-f67ab59de16332a2ea8df0fb7032ea69a0912c3bb52538649b4ed0c9fc21d9d2R636)`placement_group = None` versus `placement_group = "default"`; 
- Also in #[16437](https://github.com/ray-project/ray/pull/16437), by default the `placement_group` is set to `"default"` instead of `None` [when creating Ray Actors](https://github.com/ray-project/ray/pull/16437/files#diff-f67ab59de16332a2ea8df0fb7032ea69a0912c3bb52538649b4ed0c9fc21d9d2R500).
- However in when tune_small.py test runs,  RayXGBoostActor's`placement_group` was to `None`, …
=> [rfc] Change default value of placement group from None to "default"

xgboost_ray/data_sources/modin.py, xgboost_ray/matrix.py, xgboost_ray/tests/test_client.py
Currently we are using string comparison to check for valid modin versions `MODIN_INSTALLED = modin.__version__ >= "0.9.0"`. Modin recently released 0.10.0 last week which fails this check. Thus, if modin 0.10 is installed, xgboost-ray thinks that modin is not installed. This means that the modin CI tests are currently being skipped, and also causing xgboost-ray to not recognize modin as a valid data source (https://github.com/ray-project/xgboost_ray/issues/116). Instead, we should do a more robust version check. Also, this PR tests the simple modin example with Ray Client now that 0.10 is released.
Closes https://github.com/ray-project/xgboost_ray/issues/116
=> Support modin 0.10.0

xgboost_ray/main.py, xgboost_ray/tests/test_data_source.py, xgboost_ray/tests/test_fault_tolerance.py
Separate out `_RayXGBoostActor` class to enable inheritance in projects using xgboost-ray as a dependency
=> Separate out `_RayXGBoostActor`

xgboost_ray/sklearn.py, xgboost_ray/tests/test_sklearn.py
Adds a way to pass keyword params to `RayDMatrix` created internally in sklearn API estimators.
=> Add `ray_dmatrix_params` to sklearn API

xgboost_ray/main.py
Two `logger.warning`s replaced with `warnings.warn` in accordance with https://docs.python.org/3/howto/logging.html
=> Replace some logger warnings with user warnings

requirements-test.txt
Temporary fix to allow for CI to pass. Newest tensorboardX release (2.3) added Pillow and Torch as dependencies without specifying them in requirements. Looks to be unintentional but it breaks CI in the meantime. Once tensorboardX releases a fix it can be removed from the test dependencies here
=> Pin tensorboardX for CI

xgboost_ray/matrix.py, xgboost_ray/tests/test_matrix.py
Fixes https://github.com/ray-project/xgboost_ray/issues/131
The previous algorithm had an edge case where it was possible for one actor to get no indices. The new algorithm is based on [`numpy.array_split`](https://github.com/numpy/numpy/blob/v1.21.0/numpy/lib/shape_base.py#L739-L792) and guarantees that each actor will get indices.
=> Better algorithm for batch sharding indices

xgboost_ray/main.py, xgboost_ray/tests/test_colocation.py
When placement group setup times out, we are expected to raise a `TimeoutError` and fail immediately. When `ray.wait` times out, the first object returned will be an _empty list_, not `None`. This PR fixes the logic so that a timeout will properly route to a `TimeoutError`.
**Testing Done:** Added a new `test_timeout` test in `test_colocation.py` that tries to request an invalid resource. Without this change, the code will hang in `_train` as it waits for the actors to be prepared.
=> fix placement group timeout behavior

run_ci_examples.sh, xgboost_ray/data_sources/object_store.py, xgboost_ray/examples/simple_objectstore.py
=> Support object store references as data source

xgboost_ray/main.py
With the merge of https://github.com/ray-project/ray/pull/17527, the default behavior for capturing child tasks in placement groups has changed. By explicitly setting `placement_group_capture_child_tasks=True` in xgboost-ray, we ensure that the previous behavior is maintained.
=> Placement group capture child tasks

xgboost_ray/tests/test_fault_tolerance.py
Changes in https://github.com/dmlc/xgboost/commit/d080b5a9533c22890b976670ddb5330eb8c97041 alter a trained booster object, so raw object dumps are not equal to checkpoints anymore. 
Thus, we weaken our checkpoint continuation test by comparing parameter dumps instead of binary tree representations.
=> Compare with get_dump() instead of save_raw()

xgboost_ray/data_sources/ray_dataset.py, xgboost_ray/examples/simple_ray_dataset.py, xgboost_ray/matrix.py, xgboost_ray/tests/test_data_source.py
Ray Datasets path has been changed from `ray.experimental.data` to `ray.data` in the nightlies, breaking support here. This PR updates the imports in `xgboost_ray`.
=> Update Ray Datasets import

xgboost_ray/main.py, xgboost_ray/tests/test_end_to_end.py
Ensures that the kwargs passed to `train` are actually valid for `xgb.train()`.
=> Validate `train` kwargs

xgboost_ray/main.py, xgboost_ray/tests/release/tune_placement.py
Deprecated from Ray 1.4, will be removed in upstream: https://github.com/ray-project/ray/pull/18475
=> Remove usage of deprecated ray.services.get_node_ip_address

.github/workflows/test.yaml, README.md, setup.py, xgboost_ray/compat/__init__.py, xgboost_ray/data_sources/data_source.py, xgboost_ray/data_sources/numpy.py, xgboost_ray/main.py, xgboost_ray/matrix.py, xgboost_ray/tests/release/cluster_cpu.yaml, xgboost_ray/tests/release/setup_xgboost.sh, xgboost_ray/tests/release/tune_cluster.yaml, xgboost_ray/tune.py, xgboost_ray/xgb.py
This has been done in order to allow for lightgbm-ray to be installed without xgboost. The new install command for xgboost-ray will be `pip install "xgboost-ray[default]"`. If xgboost is not installed, `train` and `predict` methods will throw an ImportError.
=> Make xgboost an extra dependency

README.md, xgboost_ray/tests/release/run_e2e_gpu.sh, xgboost_ray/tests/release/tune_cluster.yaml
The `egg=` suffix is necessary for correct installation of `[default]` extras
=> Fix xgboost-ray[default] git install

xgboost_ray/matrix.py, xgboost_ray/tests/test_matrix.py
Conversion of a pandas dataframe to a RayDMatrix did not conserve the ordering of columns because this line would actually do a set difference: https://github.com/ray-project/xgboost_ray/blob/88c3188741650ac7c6e2383315b637c4462f65e7/xgboost_ray/matrix.py#L253
Instead we should conserve the order of the columns in the original dataframe.
Issue: https://discuss.ray.io/t/raydmatrix-reordering-dataframe-columns/3981
=> Preserve ordering of columns on conversion to RayDMatrix

xgboost_ray/main.py
Since XGBoost 1.5, DMatrix initialization for distributed training requires the Rabit context to exist as all reduce steps are carried out ahead of training to synchronize e.g. feature column distribution.
In this PR, we move the DMatrix initialization into the Rabit context.
Closes #176
=> Initialize DMatrix in Rabit context

xgboost_ray/main.py, xgboost_ray/matrix.py, xgboost_ray/sklearn.py, xgboost_ray/tests/test_end_to_end.py, xgboost_ray/tests/test_sklearn.py
Adds support for the `qid` parameter, allowing ranking to work correctly. The `group` parameter is not supported - this is also the case for XGBoost's Dask interface.
Support for LightGBM to come in the future. Not sure how that will look like, as it doesn't support the `qid` parameter.
Also fixes the `ray_dmatrix_params` arg being mandatory for `RayXGBRanker`.
Closes #186, closes #188
=> Implement ranking support

README.md
When reading environment variables, `xgboost_ray` expects them to be [prefixed](https://github.com/ray-project/xgboost_ray/blob/a43eb4a919dc751b1db0b859b7ff09f06b1a2925/xgboost_ray/main.py#L75-L120) with `RXGB_`. This updates the README to use the correct names.
=> [docs] update environment variable names in README

xgboost_ray/main.py, xgboost_ray/tests/test_tune.py
Same as in https://github.com/ray-project/lightgbm_ray/pull/29
This doesn't seem to occur with XGBoost, but the same logic is introduced for consistency. `test_tune` has been similarly deflaked.
=> Mitigate finishing too quickly

xgboost_ray/main.py
`xgboost-ray` training currently does not work on Windows. This is because we use multiprocessing in the Rabit Tracker, but the run method is not serializable, so we have to use `fork` method instead of `spawn`. (see #42). 
However, Python multiprocessing does not support `fork` method on Windows.
This PR immediately raises an error if Windows OS is identified with a better error message.
See #208
=> Fail quickly on Windows

xgboost_ray/main.py, xgboost_ray/sklearn.py, xgboost_ray/tests/test_sklearn.py, xgboost_ray/tests/test_sklearn_matrix.py
Also uses `LooseVersion` instead of our own regex-based version tuple.
=> Fix `test_num_parallel_tree` for cutting edge CI

.github/workflows/test.yaml
We should look into the root cause of the performance regressions at some point, but having CI red for days isn't a good sign of the project's health
=> Adjust CI timeouts

setup.py, xgboost_ray/main.py, xgboost_ray/tests/test_colocation.py, xgboost_ray/tune.py, xgboost_ray/util.py
There are several places where we still have code paths for legacy Ray versions. With the next release we can require newer Ray versions to be used.
=> Remove code for legacy Ray versions

xgboost_ray/main.py
Adds a verbose flag to RayParams to toggle events. Defaults to False, but open to discuss.
The main thing is that when using AIR/Tune, this logging becomes quite verbose.
=> Reduce verbosity for ray events

requirements-test.txt, setup.py, xgboost_ray/data_sources/modin.py, xgboost_ray/main.py, xgboost_ray/sklearn.py, xgboost_ray/tests/test_sklearn.py, xgboost_ray/tests/test_sklearn_matrix.py
This PR removes uses of `distutils.version.LooseVersion` in favor of `packaging.version.Version` at the suggestion of the deprecation warning generated when a user makes use of `LooseVersion`. This PR addresses one of the deprecation warnings identified in https://github.com/ray-project/ray/issues/27851. `distutils` [will be deprecated in Python 3.10 and 3.11, and removed entirely in 3.12](https://peps.python.org/pep-0632/).
- Replaced `distutils.version.Version` with `packaging.version.Version` everywhere
- Added `packaging` as a dependency in `requirements-test.txt` and in `setup.py`
I tested this on my local machine with `pytest` and all the tests that weren't skipped passed.
=> Switch to use packaging.Version from distutils LooseVersion

setup.py
Add license metadata tag to package setup 
package scanning system prevents install of packages with missing license metadata.  Unable to test this package.
=> add license metadata tag to package setup

xgboost_ray/main.py, xgboost_ray/matrix.py
XGBoost>=1.5 added a new dmatrix param, `enable_categorical`. Adding it here.
This PR also makes the detection of the case of already being in a placement group more broad and not limited to just Tune. This allows for xgboost-ray to be ran in nested tasks that are not related to Tune (this should be two PRs really, but I needed one branch to patch it for hackathon).
=> Add `enable_categorical`, better detection for being in a PG

xgboost_ray/matrix.py, xgboost_ray/tests/test_matrix.py
If qid is provided, xgb.DMatrix [requires data to be sorted by qid - see data.cc](https://github.com/dmlc/xgboost/blob/master/src/data/data.cc#L486):
https://github.com/ray-project/xgboost_ray/blob/master/xgboost_ray/matrix.py#L351
draft to add auto sorting of dataframe if qid is given and dataframe is not already sorted by qid
=> Add sort dataframe logic on qid

requirements-test.txt, xgboost_ray/main.py, xgboost_ray/session.py
Adds compatibility for xgboost>=1.7.0 by implementing changes from https://github.com/dmlc/xgboost/pull/8257 and fixes unrelated CI failures due to changes on Ray master
=> Compatibility for xgboost>=1.7.0, fix master CI

.github/workflows/test.yaml
3.6 is no longer supported in Github Actions.
=> Switch from 3.6 to 3.9 in tests

xgboost_ray/tune.py
Fixes xgboost-ray being unusable with Colab.
=> Set Tune trainable resources to 0

xgboost_ray/tune.py
If `_max_cpu_fraction_per_node` is None and passed to `placement_group`, an exception will be thrown. Currently, code in Ray doesn't discard that key if its None before passing it to `xgboost_ray.RayParams`. This will be fixed properly in Ray (https://github.com/ray-project/ray/pull/30977), but in the meantime, we add a special case here to ensure that Ray 2.2 works.
=> Add special case in `_get_tune_resources`

xgboost_ray/matrix.py, xgboost_ray/tests/test_matrix.py
Ensures that we always use distributed loading by default with Ray Datasets. Followup to https://github.com/ray-project/ray/pull/31079
=> Always detect Ray Dataset as distributed

.github/workflows/gpu.yaml, .github/workflows/test.yaml, xgboost_ray/tests/test_sklearn.py
=> Fix CI with latest xgboost

.gitignore, setup.py, xgboost_ray/main.py, xgboost_ray/matrix.py, xgboost_ray/tests/test_end_to_end.py, xgboost_ray/tests/test_matrix.py
This PR adds support for feature_weights parameter, which is xgb.DMatrix parameter since Xgboost version 1.3.0. This PR does not add this support for RayDeviceQuantileDMatrix class.
=> Add feature weights support

xgboost_ray/main.py, xgboost_ray/tests/test_client.py, xgboost_ray/tests/test_end_to_end.py
This pr closes #266
_ray_get_act_cpus  did not get the correct number set for CPU in actors, because when placement group is used, the resource name changes. In addition, set this number as nthread in param which is used to create DMatrix. @Yard1
=> Fix _ray_get_act_cpus and set nthread in param passed to DMatrix creation

xgboost_ray/matrix.py
Make `assert_enough_shards_for_actors` always pass if Ray Datasets are used, as they will be split to match the number of actors during loading.
=> Mark Ray Dataset as always having enough shards

xgboost_ray/main.py, xgboost_ray/matrix.py
xgboost 1.7.0 has extended quantile dmatrix to CPU, and unified the API. Now DeviceQuantileDMatrix is deprecated. This PR adds support for QuantileDMatrix by adding a thin wrapper.
=> Add QuantileDMatrix support

xgboost_ray/tests/test_sklearn.py
This test reverts part of https://github.com/ray-project/xgboost_ray/pull/276. It seems like the naming changes have been reverted on xgboost master, leading to failures in our sklearn tests.
=> Fix sklearn tests

xgboost_ray/data_sources/data_source.py, xgboost_ray/data_sources/ray_dataset.py, xgboost_ray/matrix.py, xgboost_ray/tests/test_data_source.py
Currently we throw an error when the number of partitions in a data source is too small for the number of workers.
However, in the case of Ray datasets, we can actually repartition the dataset ourselves.
This will also ensure our quickstart examples, such as in https://docs.ray.io/en/latest/train/train.html#quick-start-to-distributed-training-with-ray-train will work out of the box.
=> Repartition Ray dataset if number of shards is too small

.github/workflows/gpu.yaml, .github/workflows/test.yaml, setup.py, xgboost_ray/matrix.py
Python 3.7 is EOL and the Ray OSS CI has switched to Python 3.8 as well.
=> Update CI to use Python 3.8-3.10

requirements/test-requirements.txt, xgboost_ray/examples/simple_tune.py, xgboost_ray/main.py, xgboost_ray/tests/test_tune.py, xgboost_ray/tune.py
We are converging on using `train.report` throughout the Ray library code base instead of `tune.report`.
=> Use new train.report API

requirements/test-requirements.txt, xgboost_ray/main.py, xgboost_ray/tests/release/tune_placement.py, xgboost_ray/tests/test_client.py, xgboost_ray/tests/test_tune.py, xgboost_ray/tune.py
This PR simplifies the Ray Train/Tune integration for `xgboost_ray` by doing the following:
* Removes the deprecated APIs (`TuneReportCallback`, `is_session_enabled`, `callback._report`, `callback._checkpoint`)
* Unifies the checkpointing integration with Tune around `TuneReportCheckpointCallback`
* Uses the public `ray.train.get_context` API instead of detecting the train "session"
* Preps this repository to be merged into the main Ray repo.
See the corresponding Ray changes: https://github.com/ray-project/ray/pull/42111
=> Simplify checkpointing callback for Ray Train/Tune integration

xgboost_ray/data_sources/data_source.py, xgboost_ray/matrix.py, xgboost_ray/tests/test_matrix.py
This is a new pull request to replace https://github.com/ray-project/xgboost_ray/pull/298 because I'm unable to work on that branch.
I copied content from that pull requests:
Hi I added support to allow label as a list. So we can support reading data with multiple labels. This can then solve https://github.com/ray-project/xgboost_ray/issues/286.
I verified new unit tests pass. Also test_matrix.py all pass with my local set up.
I verified locally by training a xgboost model with parquet data format, it works well. So far it should work well for parquet data format. Thank you!
I verified the change works with the blow code example:
```
from sklearn.datasets import make_multilabel_classification
import pandas as pd
import numpy as np
n_classes = 5
random_state = 0
X, y = …
```
=> Add multi label support v2
