ray-project/xgboost_ray

- .github/workflow/test.yaml
- requirements-test.txt
- setup.py
- xgboost_ray/matrix.py
Adds support for github actions as CI.
> [ci] github actions

- examples/train_on_test_data.py
- xgboost_ray/__init__.py
- xgboost_ray/main.py
- xgboost_ray/matrix.py
- xgboost_ray/tests/test_matrix.py
Introduces RayDeviceQuantileDMatrix (currently untested for GPU usage) and updated much of the data loading logic.
> Matrix refactor

- setup.py
- xgboost_ray/main.py
- xgboost_ray/matrix.py
- xgboost_ray/tests/release/benchmark_cpu_gpu.py
- xgboost_ray/tests/release/cpu_large_scale.yaml
- xgboost_ray/tests/release/gpu_cluster.yaml
- xgboost_ray/tests/release/gpu_single.yaml
Full release tested support for RayDeviceQuantileDMatrix using cupy.
> Full support for RayDeviceQuantileDMatrix

- .github/workflows/test.yaml
- README.md
- examples/create_test_data.py
- examples/higgs.py
- examples/higgs_parquet.py
- examples/simple.py
- examples/simple_predict.py
- examples/simple_tune.py
- examples/train_on_test_data.py
- xgboost_ray/__init__.py
- xgboost_ray/main.py
- xgboost_ray/matrix.py
- xgboost_ray/tests/release/benchmark_cpu_gpu.py
- xgboost_ray/tests/release/create_test_data.py
- xgboost_ray/tests/test_end_to_end.py
- xgboost_ray/tests/test_fault_tolerance.py
- xgboost_ray/tests/test_tune.py
- xgboost_ray/tests/test_xgboost_api.py
- xgboost_ray/tests/utils.py
Refactor to use new dataclass `RayParams`
> Api refactor

- .github/workflows/test.yaml
- xgboost_ray/main.py
- xgboost_ray/tests/conftest.py
- xgboost_ray/tests/test_colocation.py
- xgboost_ray/tests/test_fault_tolerance.py
- xgboost_ray/tests/utils.py
- xgboost_ray/util.py
A smaller PR for implementing colocation for just the Queue and Event with the driver. Added a unit test for this as well. This PR does not include placement group support.
> Colocation for Communication Actors

- xgboost_ray/main.py
- xgboost_ray/tests/test_colocation.py
We have a growing number of private (semi-global) parameters passed to `_train()`. Instead we should just pass one training state object.
> Introduce training state dataclass, replacing private variables in _train()

- .github/workflows/test.yaml
- xgboost_ray/tests/test_colocation.py
- xgboost_ray/util.py
test_colocation has sometimes timed out: https://github.com/ray-project/xgboost_ray/issues/38.
This PR adds some more verbosity to the test so we can see some additional output the next time it times out.
Also upgrades the latest Ray wheels to 1.2.0.dev0
> Update Ray wheels and increase verbosity for test_colocation

- README.md
- xgboost_ray/tests/release/custom_objective_metric.py
> pip install in readme

- xgboost_ray/tests/conftest.py
- xgboost_ray/tests/test_colocation.py
This will hopefully deflake the colocation tests
> Remove kill callbacks from colocation tests

- .github/workflows/test.yaml
- README.md
- examples/simple_tune.py
- xgboost_ray/main.py
- xgboost_ray/tests/release/tune_placement.py
- xgboost_ray/tests/test_colocation.py
- xgboost_ray/tests/test_tune.py
- xgboost_ray/tune.py
Will need to change after https://github.com/ray-project/ray/pull/13906 is merged.
> Add get_tune_resources helper method

- README.md
- xgboost_ray/main.py
- xgboost_ray/tests/test_end_to_end.py
- xgboost_ray/tests/test_fault_tolerance.py
- xgboost_ray/tests/utils.py
This was broken, especially for multi failures
> Fix number of boost rounds after failures

- xgboost_ray/data_sources/__init__.py
- xgboost_ray/data_sources/csv.py
- xgboost_ray/data_sources/data_source.py
- xgboost_ray/data_sources/ml_dataset.py
- xgboost_ray/data_sources/modin.py
- xgboost_ray/data_sources/numpy.py
- xgboost_ray/data_sources/pandas.py
- xgboost_ray/data_sources/parquet.py
- xgboost_ray/data_sources/petastorm.py
- xgboost_ray/matrix.py
- xgboost_ray/tests/conftest.py
- xgboost_ray/tests/test_matrix.py
The current structure for data loading was a bit cluttered, and it was unclear how to add new data sources or extend existing ones. By moving data sources into their own sub package, we can set this up for future integrations.
> Re-factor data loading structure

- .github/workflows/test.yaml
- README.md
- examples/readme.py
> Update two readme examples to be runnable without adjustments

- xgboost_ray/matrix.py
- xgboost_ray/tests/test_matrix.py
> CSV strings should not be detected as distributed loadable data sources

- .github/workflows/test.yaml
- README.md
- examples/readme.py
- run_ci_examples.sh
- run_ci_tests.sh
Add unit tests for latest xgboost master
> Test on latest xgboost master

- .github/workflows/gpu.yaml
- setup.py
- xgboost_ray/__init__.py
The test now passes on my fork
> Bump version to 0.0.6, fix dependency issue for manual GPU test

- xgboost_ray/tune.py
small fix about resource population
> fix RayParam resource population

- xgboost_ray/data_sources/petastorm.py
- xgboost_ray/matrix.py
- xgboost_ray/tests/test_end_to_end.py
Fixes batch loading and petastorm loader not respecting indices
> Fix BATCH sharding

- xgboost_ray/examples/simple_predict.py
- xgboost_ray/main.py
Closes #146 
Closes #147 
cc @Yard1
> Fix resource detection + better fallback, complain about unset num_actors

- setup.py
- xgboost_ray/data_sources/dask.py
Closes https://github.com/ray-project/ray/issues/16743
> Ensure that Dask Scheduler is set for Ray-on-Dask

- .github/workflows/test.yaml
> Retry CI on failure

- setup.py
Unpin pyarrow as petastorm was updated.
> Unpin pyarrow as petastorm was updated

- xgboost_ray/examples/higgs.py
- xgboost_ray/examples/higgs_parquet.py
- xgboost_ray/examples/simple_ray_dataset.py
We aren't testing higgs ones in CI, so this slipped through the cracks.
> Fix broken examples

- xgboost_ray/data_sources/ml_dataset.py
Closes https://github.com/ray-project/xgboost_ray/issues/183
> Fix bad super()

- setup.py
- xgboost_ray/__init__.py
Updating to `0.1.9` after releasing `0.1.8`.
> [release] Bump to 0.1.9 for future development

- README.md
Adjust the readme file to take advantage of https://github.com/ray-project/ray/pull/23505
There are no user facing changes, the contents of the readme displayed on GitHub are the same as they were before.
> Adjust readme for Ray Docs

- xgboost_ray/sklearn.py
Closes https://github.com/ray-project/ray/issues/24200
> Fix sklearn docs throwing an error during build

- .github/workflows/test.yaml
- xgboost_ray/sklearn.py
Compatibility fix for the latest xgboost master
> Fix `wrap_evaluation_matrices` with xgb master

- xgboost_ray/main.py
Following https://github.com/ray-project/ray/pull/26907, we can now avoid a deprecation message when using XGBRay with 2.0.
Closes #225
> Update XGBoost-Ray by removing deprecated calls for Ray 2.0

- xgboost_ray/data_sources/modin.py
- xgboost_ray/main.py
- xgboost_ray/tests/test_tune.py
Placement group APIs are updated to use `scheduling_strategy`
> Update Ray core APIs

- setup.py
- xgboost_ray/__init__.py
> Bump version to 0.1.13

- xgboost_ray/main.py
- xgboost_ray/tests/test_tune.py
- xgboost_ray/tune.py
Upstreams changes from https://github.com/ray-project/ray/pull/30470. No need to do any changes in lightgbm-ray.
> Add `placement_options` to `RayParams`

- xgboost_ray/tests/test_sklearn.py
- xgboost_ray/tests/test_sklearn_matrix.py
Boston dataset (used in tests) is/will be removed from sklearn.
> Replace boston dataset with california housing

- setup.py
- xgboost_ray/__init__.py
> Bump version to 0.1.14

- xgboost_ray/matrix.py
See https://ray-distributed.slack.com/archives/CSX7HVB5L/p1672689833908569
> Clarify `lazy` in `RayDMatrix` docstring

- xgboost_ray/data_sources/ray_dataset.py
- xgboost_ray/tests/test_data_source.py
Slightly improves performance and majorly improves object store memory usage with Ray Datasets. Also replaces our custom logic with Ray Datasets `split` method with locality hints - meaning the behavior should be the same as in Ray Train.
> Improve Ray Datasets support

- xgboost_ray/main.py
> Mention env var in PG creation timeout message

- xgboost_ray/data_sources/modin.py
> Fix modin import with mismatched pandas version

- setup.py
- xgboost_ray/__init__.py
> Bump version to 0.1.15

- xgboost_ray/data_sources/ray_dataset.py
Closes https://github.com/ray-project/xgboost_ray/issues/269
> Fix dataset conversion with `distributed=False`

- setup.py
- xgboost_ray/__init__.py
> Bump version to 0.1.16

- xgboost_ray/sklearn.py
- xgboost_ray/tests/test_sklearn.py
Fixes CI failure with cutting edge by ensuring the docstrings replaced in sklearn integration are searched for in superclasses.
> Fix cutting edge CI failure
